var faker = require("faker");
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());
console.log(faker.commerce.productName() + "   price is: " + faker.commerce.price());